image: jangrewe/gitlab-ci-android

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew

stages:
    - build

bintray_upload:
    stage: build
    script:
        - ./gradlew clean cooee-android-sdk:artifactoryPublish -PartifactoryUser=${ARTIFACTORY_USER} -PartifactoryPassword=${ARTIFACTORY_PASS}
    only:
        - tags
    artifacts:
        paths:
            - cooee-android-sdk/build/outputs/aar
