image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  CMAKE:               "3.10.2.4988404"

before_script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

    - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
    - unzip -d android-sdk-linux android-sdk.zip

    - export ANDROID_HOME=$PWD/android-sdk-linux/
    - export ANDROID_SDK_ROOT=$PWD/android-sdk-linux/
    - export PATH=$PATH:$PWD/android-sdk-linux/cmdline-tools/bin:$ANDROID_HOME:$PWD/android-sdk-linux/cmdline-tools
    - echo y | sdkmanager --update --sdk_root=/android-sdk-linux

    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew
    - set +o pipefail
    - set -o pipefail

stages:
    - test
    - deploy

Validate MR:
  stage: test
  script:
    - echo y | sdkmanager "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86" --sdk_root=/android-sdk-linux
    - echo y | cd android-sdk-linux && avdmanager create avd -f -n testAVD -k "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86"
    - android-sdk-linux/emulator/emulator -avd testAVD -no-audio -no-window &
    - cd .. && ./gradlew cooee-android-sdk:connectedAndroidTest
    - ./gradlew cooee-android-sdk:test
    - ./gradlew cooee-android-sdk:publishToMavenLocal
  only:
    - merge_requests

Publish to JFrog:
    stage: deploy
    script:
        - ./gradlew clean cooee-android-sdk:artifactoryPublish -PartifactoryUser=${ARTIFACTORY_USER} -PartifactoryPassword=${ARTIFACTORY_PASS}
    only:
        - tags
    artifacts:
        paths:
            - cooee-android-sdk/build/outputs/aar
