image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  CMAKE:               "3.10.2.4988404"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
    - test
    - deploy

Validate MR:
  stage: test
  script:
    - apt-get -qq update && apt-get install -qqy --no-install-recommends qemu-kvm && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    - sdkmanager --verbose 'system-images;android-25;google_apis;x86_64'
    - echo "no" | avdmanager create avd -f -n api25 -k 'system-images;android-25;google_apis;x86_64' -d "pixel" -c 128M
    - echo "no" | /sdk/tools/emulator -avd api25 -wipe-data -noaudio -no-window -gpu off -verbose -qemu -vnc :2 &
    - timeout 180 /sdk/platform-tools/adb wait-for-device
    - ./gradlew cooee-android-sdk:connectedAndroidTest
    - ./gradlew cooee-android-sdk:test
    - ./gradlew cooee-android-sdk:publishToMavenLocal
  only:
    - merge_requests

Publish to JFrog:
    stage: deploy
    script:
        - ./gradlew clean cooee-android-sdk:artifactoryPublish -PartifactoryUser=${ARTIFACTORY_USER} -PartifactoryPassword=${ARTIFACTORY_PASS}
    only:
        - tags
    artifacts:
        paths:
            - cooee-android-sdk/build/outputs/aar
